### PR TITLE
Add Hubic.com file uploader support

### PR DESCRIPTION
**Pull request by Kouga-**
requested in #356

### CODE REVIEW

**Comment by Kouga-** [comment]
requested in #356

**Comment by Jaex** [comment]
Thanks, good work :)

**Comment by Jaex** [comment]
I wonder why you used WebClient. Because none of the uploaders using WebClient in ShareX and have built in methods for sending request which handles progress reporting and other stuff.

**Comment by Jaex** [comment]
Now I tried uploading to folder and it works fine :) But only have one problem that images don't show thumbnail and have no preview. So I will check it now.

**Comment by Jaex** [comment]
Unfortunately I can't find how to show thumbnail and support image preview like normal sharing.

Also I noticed that I can't set root folder to upload.

**Comment by Jaex** [comment]
I wish you checked OneDrive as example folder listing :D Because it allows to select root folder too:

**Comment by Jaex** [comment]
So are you planning to make "Root folder" selectable some how?

**Comment by Jaex** [comment]
I noticed big problem, OAuthInfo don't contains refresh token and it expires. So people need to re auth everytime because it can't refresh itself. So it is completely unusable currently.

**Comment by Jaex** [comment]
Then I need to disable this uploader before release because I can't release broken uploader.

**Comment by neico** [comment]
@Jaex Makes me wonder why you didn't fix the code up instead of just "disabling" it.

Especially after such a long timeframe where it's still not up there...

**Pull request merged**
