### PR TITLE
Add Confirmation to Abort Recording - Fixes #3287

### LINKED ISSUE #3287: Alert question after selecting Abort button.
Please that would be really nice if application would ask you for confirmation after clicking Abort button.
I just lost an hour of recording because I missed Stop button.

### PR DESCRIPTION
**Pull request by stuntguy3000**
This PR adds a lovely confirmation dialog when a recording is cancelled.

Also, allows the user to toggle this function.
image

### CODE REVIEW

**Comment by Torubloo** [comment]
Remember to add a confirmation when stopping too because i misclicked and save the recording, also one for when starting a recording, opening sharex, and taking a screenshot and closing sharex , etc

anyway i don't think this is needed but hey you can toggle it at least i guess

**Comment by stuntguy3000** [comment]
Keen to hear other people's thoughts on a confirmation for _stopping_

I'm against it on the basis stopping is usually an intentional and non destructive action, whereas abortion is destructive.

**Comment by Torubloo** [comment]
https://github.com/ShareX/ShareX/issues/3287

**Comment by stuntguy3000** [comment]
@Torubloo This PR was made *for* that issue, if you didn't catch that

**Comment by Torubloo** [comment]
ik i was tagging that issue in this pr so people can read it

**Comment by Scrxtchy** [comment]
I've pressed abort accidently about 20% of the time

**Pull request merged**
