### PR TITLE
Initial Commit of Polish translation

### PR DESCRIPTION
**Pull request by ireun**

### CODE REVIEW

**Comment by Jaex** [comment]
Hi, can you please only pull request pl.resx files because your pull request have Thumbs.db files.

Also it would be more convenient if you pull request at least project by project because like this you would need to do like 30 pull requests to complete whole translation.

Thanks.

**Comment by ireun** [comment]
I will try. :)

**Comment by Jaex** [comment]
Also I couldn't answer you in IRC because I was AFK.

**Comment by ireun** [comment]
No problem, i will work on this for a few days, then i will push a request. :)

**Pull request closed without merging**
