### PR TITLE
Support for text uploading to pastie.org

### PR DESCRIPTION
**Pull request by plutofever**

### CODE REVIEW

**Comment by Jaex** [comment]
This is problematic:

    ShareX.UploadersLib/Forms/UploadersConfigForm.resx
    7,738 additions, 13,408 deletions not shown because the diff is too large

**Comment by plutofever** [comment]
I was wondering about that. Is there an easy way to get around visual studio rearranging a bunch of code like that?

**Comment by Jaex** [comment]
I don't know any way. It must be bug in Visual Studio because designer not reorders everything unlike resx.

**Comment by plutofever** [comment]
This looks like a possible solution, [https://www.codeproject.com/kb/cs/resxmergeutility.aspx](https://www.codeproject.com/kb/cs/resxmergeutility.aspx).

**Comment by plutofever** [comment]
Any idea on what I can do to make this PR easier for you to review? I tried using that tool to reorder the original UploadersConfigForm.resx and then reordered mine, here were the results: [https://www.diffchecker.com/ojYxynOD](https://www.diffchecker.com/ojYxynOD).

**Comment by Jaex** [comment]
Web site is down:

    This page (http://pastie.org/) is currently offline. However, because the site uses Cloudflare's Always Online™ technology you can continue to surf a snapshot of the site.

**Comment by Jaex** [comment]
After 2 days still pastie page not opens, is it dead?

**Comment by Jaex** [comment]
So should I remove it? Because still web site is down.

**Pull request merged**
