### PR TITLE
Add verified result URLs to Pomf uploaders

### PR DESCRIPTION
**Pull request by ErikHumphrey**

### CODE REVIEW

**Comment by Jaex** [comment]
Really? I made them automatic so even when result urls change it will work. And you adding manual ones.

**Comment by ErikHumphrey** [comment]
Ah, the manual Result URL box was disabled (greyed out) when I tried, so I had to change the source code. Nonetheless I still got a working fix for one of them referenced in #1439

**Comment by Jaex** [comment]
Result URL box never becomes disabled what you mean?

**Comment by ErikHumphrey** [comment]
never becomes enabled I guess? I wasn't able to input my own result URL, but relaunching sharex fixed the problem so I guess it's a non-issue

**Pull request closed without merging**
