### PR TITLE
Add drag drop support for notifications with file name

### PR DESCRIPTION
**Pull request by Craftplacer**
Title says all, here's a quick demonstration:

https://user-images.githubusercontent.com/22963120/116364414-b32e9c80-a7f3-11eb-8eeb-e464da939f42.mp4

### CODE REVIEW

**Comment by Jaex** [comment]
Thanks 👍

**Comment by Jaex** [comment]
Clicking on thumbnail not running left click action anymore. That's probably why I did not add drag n drop support before.

**Comment by Craftplacer** [comment]
Thanks for telling me, I have attempted to implement a fix under another branch [`drag-drop-notifications`](https://github.com/Craftplacer/ShareX/tree/drag-drop-notifications). Please check it out and let me know whether it fixed that issue.

**Comment by Jaex** [comment]
Can you open PR for it? Will be easier for me to test it.

**Comment by Waleedov** [comment]
Mann thaaaaaaaank you so much.... best feature ever, I asked for something similar a year ago!
https://github.com/ShareX/ShareX/issues/4348

**Comment by chocolateimage** [comment]
This is such a good feature!
I wanted this feature for soooo long.

**Comment by yashpalgoyal1304** [comment]
yep, me too. (wanted this)

<-- https://github.com/ShareX/ShareX/pulls?q=is:pr+is:merged+drag+and+drop
<-- https://getsharex.com/changelog/#sharex-1350---2021-05-13

**Pull request merged**
