### PR TITLE
Fix issue #436

### PR DESCRIPTION
**Pull request by Kouga-**
Fix issue #436 

This return statement was double encoding filename hence the extra encoding on the "%" sign in the URL in clipboard.

return Uri.EscapeUriString(httpHomeUri.Uri.ToString());

### CODE REVIEW

**Comment by Jaex** [comment]
@SolidX was added that code in #371
So pull requests when fixing one thing in the other hand breaking other things :(
So I dunno which pull request is correct.

**Comment by Kouga-** [comment]
Hmm....@SolidX is right, I'll see if there is another way to fix it.

**Comment by Kouga-** [comment]
That last commit should fix both #436 and #371.

**Comment by Jaex** [comment]
Thanks

**Pull request merged**
