### PR TITLE
Simplified Chinese（zh-cn） upload

### PR DESCRIPTION
**Pull request by jiajiechan**
Simplified Chinese（zh-cn） upload

### CODE REVIEW

**Comment by Jaex** [comment]
Thanks for translation! Can you contact me from Google Talk (Hangouts) like using Gmail web messenger. Because for testings (incase I need to resize few controls etc.) and be able to reach you when I need new translations gonna need communication :)

**Comment by jiajiechan** [comment]
Hi, How do I get to test software to debug language?

**Comment by Jaex** [comment]
https://github.com/ShareX/ShareX/blob/master/ShareX/Enums.cs#L31

and

https://github.com/ShareX/ShareX/blob/master/ShareX/LanguageHelper.cs#L48

**Comment by Jaex** [comment]
So how do I ask questions without messenger.

**Comment by Jaex** [comment]
Hello?

**Comment by jiajiechan** [comment]
Hello, how do you need me?

**Comment by Jaex** [comment]
For ask questions like what I need to write to:



and for check is any control need to be resized to fit your language.

Also everytime before releasing I must contact you for you to update translations.

So, a way to contact is required.

**Comment by jiajiechan** [comment]
简体中文（ZH-CN）

my email m@jjc.im

**Comment by jiajiechan** [comment]
OK, I understand what you say, these two places have been changed.

**Comment by Jaex** [comment]
Would this be okey: 简体中文 (Simplified Chinese)
Because using country code not fits with other languages there because I didn't used code for others.

**Comment by jiajiechan** [comment]
Should be ZH-CN，Because there are many Chinese are also divided into many countries and regions，I saw REXS also use zh-cn。

**Comment by jiajiechan** [comment]
You also possible that

**Comment by Jaex** [comment]
here shows Simplified Chinese too.

**Comment by jiajiechan** [comment]
Is that, Simplified Chinese has also been applied to many countries, such as Singapore, Malaysia, etc., used in each country are different Simplified Chinese, zh-cn Simplified Chinese version refers to the Chinese mainland with.

**Comment by jiajiechan** [comment]
prc refers to the Chinese domestic (excluding Hong Kong and Taiwan)

**Comment by Jaex** [comment]
Problem is many people won't know what is zh-cn means. Am I wrong?

**Comment by jiajiechan** [comment]
You can also use the "Simplified Chinese", not much problem, several simplified Chinese language is only part of the syntax is slightly different.

**Comment by jiajiechan** [comment]
There is no problem using the Simplified Chinese

**Comment by Jaex** [comment]
I wonder how much similar zh-CN to zh-SG. If very similar then wouldn't be better use "zh-CHS" so if someone using Chinese Simplified Singapore in his Windows then ShareX will use that language automatically because zh-CHS is parent of both zh-CN and zh-SG ?

**Comment by jiajiechan** [comment]
yes

**Comment by Jaex** [comment]
Then I'm gonna rename zh-CN files to zh-CHS.

**Comment by jiajiechan** [comment]
In fact, I feel no need to share so meticulous, and looked the other software such as photoshop, windows, basically only into Simplified Chinese (zh-cn), Traditional Chinese (zh-tw), Traditional Chinese (zh-hk), other such as Simplified Chinese (Singapore) no one to translate, because they are elected Simplified Chinese (zh-cn) you can see to understand.

**Comment by Jaex** [comment]
Are you know how to use Visual Studio? If so you can test your language now. Otherwise I can compile and upload setup file for you.

**Comment by Jaex** [comment]
History form not opens because "历史:{}0" it should be {0}
fixed it now. Is there a possibility you used {0} {1} things wrong? Because it will crash ShareX.

**Comment by jiajiechan** [comment]
I will not Visual Studio, or you compile good to me, {0} I will fix this problem later.

**Comment by Jaex** [comment]
I already fixed it and gave link to setup which includes your language, so you can test it.

**Comment by jiajiechan** [comment]
Because not previously used github, now know how to update the upstream.

**Pull request merged**
