### PR TITLE
Accessibility: Keyboard Navigation

### PR DESCRIPTION
**Pull request by Paul-C-F**
Dialogs containing OK, Cancel and Close buttons can be dismissed by
hitting Enter or Escape on the keyboard, depending on the buttons
available.
Also added a Close button to the ChromeForm window.

### CODE REVIEW

**Comment by Jaex** [comment]
In color picker you need to press enter to confirm number so color can update, same for gradient form too. Probably there is many other such misuses too. Pressing enter in random control not always means closing form.

**Comment by Paul-C-F** [comment]
@Jaex I didn't modify the ScreenColorPicker but the ColorPickerForm which has an OK button.

Are you willing to review it before just closing?

I will go over the screens one more time to make sure that the Accept behavior is OK on each one of them, the Escape behavior however is MUCH needed everywhere there's a cancel button.

**Comment by Jaex** [comment]
Are you willing to review it before just closing?

What is that even means? I pulled your pull request tested it and then closed it.

**Comment by Paul-C-F** [comment]
@Jaex Did you really test it cause there is NO accept button on the screen color picker form.

Just forget it, you have attitude and I don't want to deal with it anymore, enjoy your project.

**Comment by Jaex** [comment]
I'm talking about color picker form not screen color picker form.

Who have attitude here implying that I'm telling lie to you...

**Comment by Jaex** [comment]
Color changes when you press <kbd>Enter</kbd> in numeric up down control:
https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/09/psTelywue1.mp4

**Comment by Paul-C-F** [comment]
@Jaex You were right about that, I never tested the spinner fields.

But here's one trick you didn't know, the TextChanged event is not on the property inspector but can be assigned via code, I tested and it works perfectly, way better than pressing Enter.

Now the question is, even if that was not possible, would you discard all other changes only because of the color picker form?

`public ColorPickerForm(Color currentColor)
        {
            InitializeComponent();
            Icon = ShareXResources.Icon;

            SetCurrentColor(currentColor, false);
            nudRed.TextChanged += new EventHandler(colorNum_TextChanged);
            nudGreen.TextChanged += new EventHandler(colorNum_TextChanged);
            nudBlue.TextChanged += new EventHandler(colorNum_TextChanged);
        }

        private void colorNum_TextChanged(object sender, EventArgs e)
        {
            RGB_ValueChanged(sender, e);
        }`

**Pull request closed without merging**
