### PR TITLE
Ukrainian translation update

### PR DESCRIPTION
**Pull request by 6c6c6**
Almost completed Ukrainian localization. Anyone can join the translation [here](https://crowdin.com/project/sharex-unofficial/).

### CODE REVIEW

**Comment by L1Q** [comment]
Good work! I have checked it briefly and the progress looks good, there are some issues however:
- In image effect form "Save image" text is too long, makes buttons overlap
- In dns changer form "Alternate DNS server" line is too long, texts goes behind input field
- Tools have "Повідомлення у Tweeter...", has to be "Twitter"

**Comment by 6c6c6** [comment]
Thanks for the fix. Today I'll try to add more translated strings and create another pull.

**Comment by L1Q** [comment]
You don't have to create more pulls, just commit more changes to your branch

**Comment by 6c6c6** [comment]
> 
> 
> You don't have to create more pulls, just commit more changes to your branch
Well, though, one extra file was added to the repo to integrate with Crowdin.

**Comment by Jaex** [comment]
Thanks!

**Pull request merged**
