### PR TITLE
Remove Yandex DNS

### PR DESCRIPTION
**Pull request by PerchunPak**
Yandex is russian Google.
[Yandex supports invasion to Ukraine](https://medium.com/dfrlab/yandex-suppresses-ukraine-war-information-for-russian-internet-users-caadfed968b5).
Yandex is blocked in Ukraine.
And the worst, Yandex works with russian government ([1](https://web.archive.org/web/20201020002100/https://zona.media/news/2019/11/18/yandex), [2](https://web.archive.org/web/20210304215406/https://www.stopfake.org/uk/yandeks-uzgodyv-iz-fsb-pytannya-shhodo-peredachi-klyuchiv-shyfruvannya/)).

### CODE REVIEW

**Comment by cattyngmd** [comment]
Ok and?

**Comment by demirdegerli** [comment]
Refers to a political issue, invalid PR.

**Comment by demirdegerli** [comment]
Modifying the code just for political topics makes no sense. Only project maintainers should start campaigns in the project *in my opinion*.
Also there are radical statements like "Yandex is russian Google". OP could open a pull request that adds an opt-in feature for this. And the reason should be "unavailable service".

**Comment by PerchunPak** [comment]
> Only project maintainers should start campaigns

I have not started any campaigns. This PR simply removes an insecure DNS provider from the list of choices.

> Also there are radical statements like "Yandex is russian Google".

I don't see anything radical in facts. Yandex has alternatives for almost everyone of Google's services. If you think that Yandex is a Netherlands-based company (because it is registered in the Netherlands), [listen](http://www.plam.ru/bislit/runetologija_kto_upravljaet_russkim_internetom/p17.php) to one of its creators, Ilya Segalovich.

> > You are a Netherlands company.
> 
> > No, we are a russian company. Is "Gazprom-Media" a Cypriot company? Is Google a Delaware company, since it is registered there? ... Let me explain this analogy. There is a company that was created by russian people with russian money, which works in moscow, pays 2,500 people a salary, pays taxes on that salary, works in russia, and creates products for russia. This company is called russian. At the same time, it is incorporated abroad. Due to the lack of a proper law on joint stock companies in russia, foreign shareholders are afraid to create a legal entity here.

> You could open a pull request that adds an opt-in feature for this.

I'm okay if someone implements at least a disclaimer, but I will not do it because of a lack of knowledge in C#.

> And the reason should be "unavailable service".

I do not really understand why it should be "unavailable". Unavailable in Ukraine? Well, everyone knows that. I do not think that anyone will refuse stolen data just because it's from non-[CIS](https://en.wikipedia.org/wiki/Commonwealth_of_Independent_States) countries.

**Comment by demirdegerli** [comment]
> This PR simply removes an insecure DNS provider from the list of choices.
You just said it, it's a list of choices. Users can change the DNS to another one if they think it's insecure. I maybe wrong, but this PR will likely not be merged.

**Review by farkon00 — APPROVED** [review]

**Comment by PerchunPak** [comment]
Reopen this please

**Pull request closed without merging**
