### PR TITLE
Adding Japanese Language Support

### PR DESCRIPTION
**Pull request by kanaxx**
I have created the resource files of Japanese translation. Could you please check and merge them if they are correct.
Thank you for your consideration in advance.

### CODE REVIEW

**Comment by Jaex** [comment]
Thanks for translation.

**Comment by kanaxx** [comment]
Thanks for your working.

**Comment by Jaex** [comment]
If you want, you can test it using dev build: https://getsharex.com/docs/dev-builds

**Comment by kanaxx** [comment]
Thanks for your advice.
I have installed 13.2.2 dev version of ShareX, but I can't find any resource files and ja-JP dir in my installed dir.  How can I find Japanese resource files?

**Pull request merged**
