### PR TITLE
Add VideoBin support

### PR DESCRIPTION
**Pull request by corey-**
Add support for videobin.org as requested in #714

### CODE REVIEW

**Comment by Jaex** [comment]
Thanks.

**Comment by Jaex** [comment]
I think your computer time is wrong, https://github.com/ShareX/ShareX/commits/master in here always showing your commit in top like this:

**Comment by corey-** [comment]
Huh, sorry about that. Yes it appears my computer date got set a day ahead somehow.

**Comment by k3d3** [comment]
@corey- this uploader doesn't work.

**Comment by corey-** [comment]
@k3d3 I just tested it and it works fine. Videobin only accepts .ogv files (even though they say they'll convert other formats, haven't gotten them to work), so what you need to do is go Task Settings > Screen Recorder, then check the box that says "Run CLI afterwards:". Then click profiles, add a new profile. Make the "Path:" the path to ffmpeg.exe, "Arguments:" should be `-i %input %output`, and "Extension:" should be `ogv`.

**Comment by k3d3** [comment]
ah. that should probably be specified somewhere.

**Pull request merged**
