### PR TITLE
Support Windows Share

### LINKED ISSUE #3605: [Feature request] Support Windows Share
First of all - well done for building such a great tool!

One feature that's definitely missing is support for windows 10 sharing system. More and more apps allow you to share their content within Windows, and it would be great if ShareX was capable of accepting images, links and text from other apps.

Especially with the upcoming release of a new snipping tool within Windows and Edge being not so bad anymore, being able to share content to your default ShareX location would make a huge difference.

### PR DESCRIPTION
**Pull request by yinyue200**
fix #3605

### CODE REVIEW

**Comment by Abu3safeer** [comment]
is this only working if sharex is installed via windows store? 
or it will work even using standalone\Steam version?

**Comment by yinyue200** [comment]
@Abu3safeer It should be packaged as appx first in order to  be working.

**Comment by Abu3safeer** [comment]
As I know appx is only through windows store, that means I have to uninstall it and use windows store version instead.

**Comment by yinyue200** [comment]
@Abu3safeer Yes. Or you can just install a appx file without the Store

**Comment by Abu3safeer** [comment]
Installing appx file without store requires developer features, I don't prefer to use this way.
image

**Comment by Abu3safeer** [comment]
No problems, I will wait and see what will happen later.

**Comment by yinyue200** [comment]
@Jaex How to make this pr be merged😂

**Comment by yinyue200** [comment]
@Jaex Could you review the pull request? Thanks

**Comment by yinyue200** [comment]
rebased with lateast commits

**Comment by yinyue200** [comment]
@Jaex

**Comment by yinyue200** [comment]
😥

**Comment by karimcambridge** [comment]
Activity guys, let's get this in!

**Comment by Vectorsmiracle** [comment]
并非必须是appx应用才能使用windows share，firefox浏览器原生可以通过windows share分享网页。

**Comment by yinyue200** [comment]
@Vectorsmiracle I can't find the Share feature in Firefox. Could you show a image to me.

**Comment by Vectorsmiracle** [comment]
[cid:image003.png@01D5198A.729B9DC0]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Yue Yin <notifications@github.com>
发送时间: Sunday, June 2, 2019 12:22:27 PM
收件人: ShareX/ShareX
抄送: Vectorsmiracle; Mention
主题: Re: [ShareX/ShareX] Support Windows Share (#3894)


@Vectorsmiracle<https://github.com/Vectorsmiracle> I can't find the Share feature in Firefox. Could you show a image to me.

―

**Comment by Vectorsmiracle** [comment]
> 
> 
> @Vectorsmiracle I can't find the Share feature in Firefox. Could you show a image to me.

firefox共享

**Comment by yinyue200** [comment]
@Vectorsmiracle It's not the feature talking in the pull request. The feature in Firefox means share content to other app. But the feature discussing in the pull request is about share content to ShareX

**Comment by Azhe403** [comment]
up, merge

**Comment by Vectorsmiracle** [comment]
The app store updated a Microsoft office outlook desktop integration app, the app is to add the desktop outlook to the share menu.
图片

**Comment by yinyue200** [comment]
@Jaex @lucario @McoreD @sylveon @Xenthys How do you think of the pr

**Comment by yinyue200** [comment]
Now , the operation of uploading files will be invoked after sharing to sharex. Any one want to add an option to allow Sharex to display the captured window?

**Comment by yinyue200** [comment]
At present, we have only added the feature which make sharex as an share target. If you want to add the feature to share the content from sharex , please click like on this comment.

**Comment by yinyue200** [comment]
Now it support share content from ShareX

**Comment by yinyue200** [comment]
批注 2019-07-29 020600

**Comment by yinyue200** [comment]
@Jaex @lucario @McoreD @sylveon @Xenthys
review the pr, please

**Comment by sylveon** [comment]
I have no control on whether a PR can be merged or not, please stop pinging me in this conversation.

**Comment by sylveon** [comment]
Also, for a PR to be merged it needs to at least be buildable - your PR doesn't builds in any configuration but the WindowsStore one.

**Comment by yinyue200** [comment]
CI failed again. But it not caused by my code. 😂
firefox_2019-07-29_02-46-46
firefox_2019-07-29_02-46-54

**Comment by Azhe403** [comment]
up up

**Comment by yinyue200** [comment]
@Jaex please review this pull request. please...😥

**Comment by sylveon** [comment]
Lack of activity by him in this thread should be pretty indicative that he doesn't wants this PR merged.

**Comment by Bluscream** [comment]
so the new way of saying no is saying nothing? i don't think that's how it works.

**Comment by sylveon** [comment]
It's how it always worked in this repo.

**Comment by Bluscream** [comment]
Reminds me of linus thorvald. Another autist

**Comment by ImSkully** [comment]
The next version of Windows will be released before this gets merged and this will become useless.

**Comment by yinyue200** [comment]
now I'm tired of constantly updating this never-merged pull request to make it compatible with the latest master. If anyone is interested in continuing this thing, you can contact me for any help.

**Pull request closed without merging**
