### PR TITLE
Check limit before uploading to Streamable

### PR DESCRIPTION
**Pull request by JeremyShih**
Streamable limits video over 1GB and longer than 10 minutes for direct file uploads. And I hope to check if video is under limitation before uploading starts.

### CODE REVIEW

**Comment by Jaex** [comment]
```using (FileStream fs = stream as FileStream)```

How this gonna work for non files?

I understand checking file size but checking video duration there is not good idea and can yield wrong results depending on whats uploading.

**Comment by JeremyShih** [comment]
non-files? for example?
Users could only select file with OpenFileDialog or select files or folders and then click the "upload with ShareX" in the context menu for upload, right?

**Comment by Jaex** [comment]
It also supports MemoryStream for example for gif. So you can't assume it is always FileStream.

**Comment by JeremyShih** [comment]
What about checking the limits only in video uploading?
I have tried uploading a video file and uploading after screen recording, in both case the 'stream' will be 'FileStream'.
The settings shown in pic below.

**Pull request closed without merging**
