### PR TITLE
Added Streamable support.

### PR DESCRIPTION
**Pull request by lawlmart**
Here at Streamable we've been getting a lot of requests from our users in the video gaming and sports communities to add support to ShareX. So we did! It's a video host so it's meant to be used with screen capture. The only slight complication is that there's a delay after the upload during which we transcode the video; I added a second progress counter during that time so the user isn't left hanging. Let me know if this isn't the preferred method.

### CODE REVIEW

**Comment by lawlmart** [comment]
I just checked our logs and we haven't experience any outages today. Which web browser are you using? How about http://streamable.com?

**Comment by lawlmart** [comment]
I take that back, it looks like we were having some issues in your region due to high traffic. It should be back up now.

**Comment by Jaex** [comment]
So just because there was high traffic from Turkey you were banned my country access to your website and now reopened it?

**Comment by Jaex** [comment]
I am doing some researching and I found out that even 8 months ago Turkish people were unable to access your web site so it was obviously not an issue and I suppose you just blocked us to save some bandwidth? And I find this as a highly racist act.

**Comment by petrosian** [comment]
Hey @Jaex, I'm the founder of Streamable -- really sorry for the confusion here.

I can confirm that video uploading in some regions and countries (including Armenia, my home country!) has been disabled over the past year. We are a small team of 3 people, and since we are offering a free service we have often struggled to keep the video encoding servers alive under all of the traffic. Video playback (e.g. https://streamable.com/moo) has never been rate-limited in any country.

Our encoding servers are pretty stable now so I've removed all of the geographic rate-limiting code and there should be no more issues like the one you've experienced. Please accept my apology for this crude hack to our scaling problems. If you still think I'm a racist and don't want to merge the pull request, that's fine too -- but please don't blame @lawlmart as he had nothing to do with this decision.

**Comment by Jaex** [comment]
Thanks for explanation, instead of telling it was just some issues in my region. Merged it.

**Comment by Jaex** [comment]
I noticed now many control sizes broken in UploadersConfigForm. I couldn't see this before merge because GitHub was not showing resx diffs and even if it show still difficult to notice what is wrong because of 2500 line changes in resx.

**Comment by lawlmart** [comment]
Very odd, I'm looking into it now.

**Comment by Jaex** [comment]
I tested it now and it works good. But quality isn't very bad?

Streamable: 

Actual video:

**Comment by lawlmart** [comment]
Wow, it is. It looks like we're incorrectly identifying the bitrate. Working on a fix now, thanks for the heads up.

**Comment by pangeacake** [comment]
Upload failed once.. might be because the recording was a little longer

stacktrace:

```
Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Int64'. Path 'percent', line 1, position 240. ---> System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.Streamable.TranscodeFile(UploadResult result)
   at ShareX.UploadersLib.FileUploaders.Streamable.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)
```

**Comment by lawlmart** [comment]
We can fix this on our end, pushing it out now.

**Comment by mathonwy1** [comment]
Hi there.

Thanks a lot for your hard work on this.

I do a lot of capture of sports clips and upload them to streamable.

I've been looking for an easier way to do it and I came across this program.

My question is, is it possible to put the name of the file name as the streamable title of the clip?

I like to keep my clips orderly and having it properly titled is a big part of it.

Thank you!

**Pull request merged**
