### PR TITLE
#1737 Updated MegaApiClient to 1.3.0. Fixed upload progression reset issue

### PR DESCRIPTION
**Pull request by gpailler**
- Updated MegaApiClient to 1.3.0
- MegaApiClient 1.3.0 uses new .Net HttpClient (builtin in .Net 4.5 and usable with additional Nuget packages for .Net 4.0)
- Configured upload pack option to merge upload chunks in 512MB fragments. It's a workaround to fix issue #1737.

### CODE REVIEW

**Comment by gpailler** [comment]
@Jaex MegaApiClient depends of HttpClient now. There is additional assemblies from Microsoft to include in the installer (because ShareX targets .Net 4.0). Is it a showstopper for you?

**Comment by Jaex** [comment]
Sorry but I don't prefer additional dependencies for uploader.

**Comment by gpailler** [comment]
I understand. I'm preparing a 1.3.1 version using old HttpWebRequest for .Net 4.0

**Comment by gpailler** [comment]
@Jaex I updated the code to use new 1.3.1 version without HttpClient dependency. Was the reference to MegaApiClient in ShareX project required?

**Comment by Jaex** [comment]
I can compile without reference in ShareX project so it not need. Thanks.

**Pull request merged**
