### PR TITLE
added StartingStepNumber option for AnnotationOptions #3611

### PR DESCRIPTION
**Pull request by Fyers**
Added a shape options for step counter, where the user can set the starting value as suggested by #3611

### CODE REVIEW

**Comment by Jaex** [comment]
Are you not hiding that option when other tools selected?
Also I'm not sure why you setting this: `AnnotationOptions.StartingStepNumber = 1;`
I can't see that you set initial value of control too.

**Comment by Fyers** [comment]
> Also I'm not sure why you setting this: `AnnotationOptions.StartingStepNumber = 1;`
I set `AnnotationOptions.StartingStepNumber = 1;` because else it would always start with the previous selected first value. So if I put 8 as the first value and save my image, the next image would also start at 8 because the value is never reseted.

Would it be neater to reset the initial value in the eg. ShapeEditor's `form_Shown` or in an other place?

**Comment by Jaex** [comment]
If you were not planning to keep starting step number permanent then why you stored it in settings instead of storing it somewhere inside ShapeManager.

**Comment by Jaex** [comment]
Thanks.

**Comment by WiliTest** [comment]
I don't understand, is it possible to change the step? How, where? 
One intuitive way would be simply to either add a menu on the step button, or (maybe easier) to change the number when we click on it.

**Pull request merged**
