### PR TITLE
Czech Translation

### PR DESCRIPTION
**Pull request by Baegus**
Sorry, my GitHub desktop app was acting strange before, here it is in one commit.

### CODE REVIEW

**Comment by Jaex** [comment]
Thanks.

**Comment by Jaex** [comment]
Are you not planning to complete translation?

**Comment by Baegus** [comment]
Sorry, I've been pretty busy lately. I'm planning to complete it when I'll have more free time.

**Comment by radim-ek** [comment]
So, can I continue with your work @Baegus ? I have a few free time and many of enthusiasm for this project :)

**Comment by Baegus** [comment]
Feel free to continue!

**Pull request merged**
