### PR TITLE
Updated Simplified Chinese

### PR DESCRIPTION
**Pull request by jiajiechan**
-Add six local translation

### CODE REVIEW

**Comment by jiajiechan** [comment]
hi, Jaex.
-I found a few places in the sharex missing translation items.
-Also troublesome Jaex compiled about the latest sharex test program to test me Simplified Chinese language.

thanks.

**Comment by Jaex** [comment]
Those texts are custom hotkey descriptions. When you can write your own description there how am I supposed to make them translatable? But why it is Turkish in your ShareX instead English I'm not sure.
Didn't understood your second question.

**Comment by Jaex** [comment]
By default descriptions empty which using hotkey description and it works fine with translation. When I change language those descriptions changing too.

**Comment by jiajiechan** [comment]
I want to get sharex test, test the last update in Chinese

**Comment by Jaex** [comment]
resx files can't work without compile so without Visual Studio you can't make it work :(
By the way I figured why that hotkey descriptions stuck in one language and fixing it now. So description when empty it can use current language hotkey info.

**Comment by Jaex** [comment]
Alright fixed hotkey description problem:

So if hotkey description is empty (emtpy by default) then it will show language based text :)

**Comment by Jaex** [comment]
Latest beta: https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/01/ShareX-9.6.0-setup.exe
You must edit descriptions of hotkeys to be empty. It is by default empty now but because you using your config it won't be empty for you.

**Pull request merged**
