### PR TITLE
Use a SharedAssemblyInfo to minimize duplication

### PR DESCRIPTION
**Pull request by sylveon**

### CODE REVIEW

**Comment by Jaex** [comment]
I don't think `[assembly: AssemblyDescription("Screen capture, file sharing and productivity tool")]` should be used for library files.

**Comment by sylveon** [comment]
If you look at the removed lines, it was used in libraries too, so I left it as it was.

**Comment by Jaex** [comment]
It is not?

**Comment by sylveon** [comment]
Ah yes, my bad. I'll fix that

**Pull request merged**
