### PR TITLE
Added Mexican Spanish language [es_MX]

### PR DESCRIPTION
**Pull request by absay**
New language for the Mexican variant.

### CODE REVIEW

**Comment by Jaex** [comment]
You modified these files by mistake I think:

* StickerPackForm.resx
* QRCodeForm.es.resx

**Comment by absay** [comment]
Yes, they were accidentally edited and managed to make it to my commits. Sorry about that! I reviewed them and aside from that extra line, the change in the QRCodeForm.es.rex file is a valid correction over the original translation.

I'm planning on improving the current Spanish localization [es] the best I can anyway since, besides being incomplete and apparently abandoned, the translations have lots of issues. It's pretty evident it was carelessly made (see #3447).

**Comment by Jaex** [comment]
Thanks.

**Comment by Jaex** [comment]
Is this correct?

**Comment by absay** [comment]
Hi Jaex,

Yes, that is correct. Thanks.

**Pull request merged**
