### PR TITLE
Added an "offline mode"

### PR DESCRIPTION
**Pull request by C03**
Implemented an "offline mode" for https://github.com/ShareX/ShareX/issues/4521
-Adds "OfflineMode" in Application Settings > Advanced > Application 
-Hides everything requiring connectivity (OCR, Uploading, Debug, Proxy etc)

The only issue I had with this was 3 items on the "After Capture Tasks" drop-down menu:

If you could tell me where these menu items are located then I'll be able to hide them as well.

### CODE REVIEW

**Comment by C03** [comment]
Apologies for the styling issues

**Comment by Jaex** [comment]
I don't see point of this option. If you don't want to upload just don't press those buttons. And if it is bothering anyone, people are feel free to use screen capture software which have no upload capabilities, such as built in "Screen snip" of Windows 10.

You may tell what if users accidentally press upload buttons, thats why I added "DisableUpload" option, which will make sure upload not executes.

**Comment by C03** [comment]
"DisableUpload" doesn't disable OCR? The user was requesting that the application would run in a way that their images couldn't accidentally be uploaded. 

Sure this feature may be not widely used but that's why it's hidden away in the advanced settings - the purpose of this feature is for those who work in sensitive environments where accidental data leakage can have some pretty bad effects depending who manages to get access to that data. 

The suggestion of using "Snip & Sketch" is invalid for the following reasons:
-It's for Windows 10 only
-No GIF support
-Editor is mediocre
-Lacks the ability to auto copy the image to the clipboard

But if you still disagree with this feature then could you at least close the issue requesting this feature?

**Comment by sylveon** [comment]
Unfortunately, ShareX does not support corporate environments really well.

The lack of group policy controls means for example any user can disable `DisableUpload` and upload private information away, and as you've noticed things like OCR ignore that entirely despite uploading your data to a service.

The issue I see here, and probably what @Jaex means, is that your offline mode is almost a duplicate for `DisableUpload`. Why not make your PR improve that to also hide features that upload, instead of adding an entirely new setting?

**Comment by C03** [comment]
Thanks for the response, that's a good shout. I can implement this into `DisableUpload` option rather than having it as a separate feature. 

In regards to corporate environments, I was more aiming this at users who work as freelancers where accidentally uploading pictures of their code/designs can actually be a breach their contract.

@Jaex does this sound like a reasonable change?

**Pull request closed without merging**
