### PR TITLE
PT-PT Language

### PR DESCRIPTION
**Pull request by FarewellAngelina**
Translated all strings to PT-PT Language, please pull this.
Thank you.

### CODE REVIEW

**Comment by Jaex** [comment]
Thanks for translation! But these should not be included:

**Comment by Jaex** [comment]
I noticed pt-pt files missing in some places like here:

**Comment by FarewellAngelina** [comment]
What path is that from? Because i see them on ShareX/ShareX.HelpersLib/Properties/ , do you have more examples?

**Comment by Jaex** [comment]
Interesting for some reason that specific single file did not show up in Visual Studio when all other resx files showed up but now I can see it. Not sure why.

`Português (Portuguese)` for language menu right?

**Comment by FarewellAngelina** [comment]
Yes, that's right.

**Pull request merged**
