### PR TITLE
Add Hebrew translation

### PR DESCRIPTION
**Pull request by E-RELevant**
Full translation for the Hebrew language.

### CODE REVIEW

**Comment by Jaex** [comment]
It is not full, missing significant amount of translations.

**Comment by E-RELevant** [comment]
> It is not full, missing significant amount of translations.

What did I miss? I used the [ResX Resource Manager](https://github.com/tom-englert/ResXResourceManager) to load the [ShareX](https://github.com/ShareX/ShareX/tree/develop/ShareX) sub-directory. Do I need to have acted differently? I did my best to understand the [documentation's requirements](https://getsharex.com/docs/translation).

**Comment by E-RELevant** [comment]
> It is not full, missing significant amount of translations.

> It is not full, missing significant amount of translations.

Can you please mention what did I miss @Jaex? I used the [ResX Resource Manager](https://github.com/tom-englert/ResXResourceManager) to load the [ShareX](https://github.com/ShareX/ShareX/tree/develop/ShareX) sub-directory. Do I need to have acted differently? I did my best to understand the [documentation's requirements](https://getsharex.com/docs/translation).

**Comment by E-RELevant** [comment]
> It is not full, missing significant amount of translations.

Could you please mention what did I miss and where do I find these missing translations, @Jaex? I used the [ResX Resource Manager](https://github.com/tom-englert/ResXResourceManager) to load the [ShareX](https://github.com/ShareX/ShareX/tree/develop/ShareX) sub-directory. Do I need to have acted differently? I did my best to understand the [documentation's requirements](https://getsharex.com/docs/translation).

**Comment by E-RELevant** [comment]
> It is not full, missing significant amount of translations.

@Jaex As far as I know, I have now translated it all. If there is anything else missing, please let me know.

**Comment by Jaex** [comment]
Thank you for the translation! Sorry for the late response.

**Pull request merged**
