### PR TITLE
Actions toolbar can now be placed on other monitors.

### LINKED ISSUE #2354: Actions toolbar is locked on one monitor
It is impossible to move Actions toolbar to any monitor other then the main one.

### PR DESCRIPTION
**Pull request by L1Q**
I used answers in this thread as a solution http://stackoverflow.com/questions/1317235/c-get-complete-desktop-size

Fixes #2354

### CODE REVIEW

**Comment by Jaex** [comment]
Current way is not allows moving toolbar to top of taskbar because toolbar can stay behind taskbar even when it is top most window. You broken that so toolbar can disappear under taskbar now.

**Comment by L1Q** [comment]
Is taskbar a special case? Are there other elements I should think of?

**Comment by Jaex** [comment]
Method I used should be able to handle it in multi monitor. But because I don't have multi monitor not sure what is wrong.

**Comment by L1Q** [comment]
For some reason "working area" is only one monitor.

**Comment by Jaex** [comment]
Try using this: `return Screen.AllScreens.Select(x => x.WorkingArea).Combine();`

**Comment by L1Q** [comment]
Cool! It worked!

**Comment by Jaex** [comment]
Is it handle taskbar case too?

**Comment by L1Q** [comment]
Yes, I can move it to other screen, but not over taskbar.

**Pull request closed without merging**
