### PR TITLE
Dont use canonically escaped url

### PR DESCRIPTION
**Pull request by v0l**
https://msdn.microsoft.com/en-us/library/system.uri.originalstring(v=vs.110).aspx

https://github.com/ShareX/ShareX/issues/1590

### CODE REVIEW

**Comment by Jaex** [comment]
AbsoluteUri: `Skype%E2%84%A2_-_quazi_node_Skype%200tFSqEiv.png`
OriginalString: `Skype%E2%84%A2_-_quazi_node_Skype%200tFSqEiv.png`

You change makes no difference?

**Comment by v0l** [comment]
sc

The `&lrm;` seems to get removed when using AbsoluteUri. 

So the Url returned isnt matching the filename

**Comment by Jaex** [comment]
I tested it with file name `Skype™` which is what he used I think in that issue.

**Comment by v0l** [comment]
No i think its from the `%t` he has on the file naming, it takes the name from window capture. 
The window title that gets captured includes this extra marker.

**Comment by Jaex** [comment]
He gave this link: `http://storage.catalogloader.com/screenshots/yar/Skype%E2%84%A2_-_quazi_node_Skype_2016-10-03_10-53-21_0tFSqEiv.png`

Which converts to `Skype™`.

**Comment by v0l** [comment]
Yep that's the link that comes from AbosulteUri but the actual filename includes the left-right marker, i tested in similar conditions as he has with SFTP.

**Pull request merged**
