### PR TITLE
update zh-cn.resx

### PR DESCRIPTION
**Pull request by xkonglong**
- 专业词汇一致性:

   + 比如 capture  统一翻译为 "截图", 取消"捕获,捕捉" . 
   + 比如 upload 统一翻译为"上传" ,取消"上载".

- 修复了部分错误翻译( Fix error )
- 清理部分无需翻译的字母和单词,比如 ShareX

--English Version --

- Updated untranslated words.
- Unified word translation.
- Fixed some incorrect translations.
- Cleaned up words that don't need translation, for example: ShareX.

### CODE REVIEW

**Comment by xkonglong** [comment]
> We don't know Chinese.

English description added!

**Comment by Nnn990087** [comment]
Wam

**Comment by Jaex** [comment]
I see a lot of changes you did in english resx files which reverts my changes.

**Comment by xkonglong** [comment]
很遗憾中文语言没有通过审核, 已编译的语言包我已经发布到fork的分支.有需要的可以自行下载.
https://github.com/xkonglong/ShareX/releases

--- English  --

Nothing,  do not mind.

**Comment by AnzhiZhang** [comment]
> 很遗憾中文语言没有通过审核, 已编译的语言包我已经发布到fork的分支.有需要的可以自行下载. https://github.com/xkonglong/ShareX/releases
> 
> --- English --
> 
> Nothing, do not mind.

Actually, this English is wrong.

He means

> I am sorry you do not merge my changes, I forked it and made a release for my changed, you can download it here.
> https://github.com/xkonglong/ShareX/releases

**Comment by AnzhiZhang** [comment]
@xkonglong What should you do is just merge the newest commit from develop branch into your branch, then the only changes in this PR will be changed you want.

**Comment by xkonglong** [comment]
中文资源文件经过长期不同人员的翻译, 存在很多不一致的问题, 但是显然由于我的改动较大, 让源作者不敢合并. 

由于最近下沉社区支援疫情, 而且我还跟进多个开源项目.   有鉴于 ShareX 的翻译和沟通并不是很方便, 而且 ShareX 并不是我的主力截图软件, 所以大概率不会跟进这个项目. 

感谢您的建议. 


---- English ----

Nothing, do not mind.

**Comment by AnzhiZhang** [comment]
> 中文资源文件经过长期不同人员的翻译, 存在很多不一致的问题, 但是显然由于我的改动较大, 让源作者不敢合并.
> 
> 由于最近下沉社区支援疫情, 而且我还跟进多个开源项目. 有鉴于 ShareX 的翻译和沟通并不是很方便, 而且 ShareX 并不是我的主力截图软件, 所以大概率不会跟进这个项目.
> 
> 感谢您的建议.

Machine Translation

The Chinese resource files have been translated by different people over a long period of time, and there are many inconsistencies, but apparently the source authors are afraid to merge them because of the large changes I have made.

Due to the recent sinking of the community to support the epidemic, and the fact that I am also following several open source projects. Since ShareX is not very easy to translate and communicate with, and ShareX is not my main screenshot software, I will probably not follow this project.

Thanks for the suggestion.

---

I think is the author's responsibility to merge newest changes in, and provide the actually change in the PR.

**Pull request closed without merging**
