### PR TITLE
Streamable upload limit

### PR DESCRIPTION
**Pull request by JeremyShih**

### CODE REVIEW

**Comment by stuntguy3000** [comment]
Apart from my review, you seem to have a lot of unnecessary modified files.

@JeremyShih Maybe it is worth cleaning up this PR and merging your commits?

**Comment by JeremyShih** [comment]
There are only 2 files that I have modified.
In "Streamable.cs" for checking method and csproj for adding reference to Shell32.
Actually, I didn't get what you mean. Could you explain more clearly?

**Comment by stuntguy3000** [comment]
Personal preference here, I would merge the 8 commits into 1 - this is what I am referring to.

**Comment by keichinger** [comment]
@stuntguy3000 the PR can be squashed when merging :)

**Comment by JeremyShih** [comment]
I studied how to merge and just succeeded.
But I didn't get what keichinger's meaning until now...
https://stackoverflow.com/questions/35948131/github-squash-commits-from-web-interface-on-pull-request-after-review-comments
The owner could choose to squash the commits.

**Pull request closed without merging**
