### PR TITLE
Implemented Undo/redo function on image editory

### PR DESCRIPTION
**Pull request by gregorygregio**
I have reworked the existing implementation of the undo (CTRL+Z) funtion and implemented a redo (CTRL+Y) one.
First I created the ImageEditorMemento class to store a state of the Image being edited, by keeping  the list of shapes drawn and the Bitmap canvas. I decided to have a constructor with only Shapes in order to avoid cloning and storing the whole Image all the time.
image

Next I added two stacks of this ImageEditorMemento class in to the shape manager to keep all the past states of the editor and the undone ones.
image

Then I have created two methods that create and stack the current state of the editor. One will store just the Shapes list and the other will store both the Shapes and the canvas.
image

Finally I have added the Undo and Redo methods, that will unstack the past state or the undone state and restore them in the Shapes list and updating the canvas when it is not null.
image

The previous UndoShape method was replaced by the Undo. 

Also a menu item was added for the Redo function under the Undo one.

fixes: #4079

### CODE REVIEW

**Comment by Jaex** [comment]
ImageEditorMemento must have [IDisposeable](https://learn.microsoft.com/en-us/dotnet/api/system.idisposable) and memento list must be disposed when Image Editor is closing. Also while consuming the stacks make sure those mementos are disposed too.

For example you are doing `redoMementoStack.Clear();` but that list must be disposed before clearing to make sure all bitmaps are disposed. Otherwise it will be up to garbage collector to eventually dispose it. But it is better to dispose Bitmap yourself than letting garbage collector do it.

**Comment by Jaex** [comment]
Also you may want to have "ImageEditorHistory" class and store two list in it. Then you can implement [IDisposeable](https://learn.microsoft.com/en-us/dotnet/api/system.idisposable) to that class too. And then add Undo & Redo functions in it. That way it would be cleaner code.

**Comment by gregorygregio** [comment]
Commited the requested changes. The memento class now implements IDisposable and is disposed when the editor is closed.
I have created the ImageEditorHistory class to encapsulate the stacks and the undo/redo behavior.

However I can't dispose the memento that was poped from the stack beacuse it's shapes list is being assigned to the ShapeManager.Shapes list, so if I dispose it, all shapes in the editor would be deleted. Unless I duplicate the shapes list again before assigning it to the ShapeManager.Shapes list, but I am not sure if that would be necessary, since the shapes would be disposed onde they are not used by the editor anymore. What do you think about it?

**Comment by Jaex** [comment]
Great work!

**Comment by Jaex** [comment]
Past 4 hours I'm fixing undo/redo related bugs but more and more appearing. And now I realized that when you pan/zoom/change editor window size etc. then undo inserts shapes in wrong positions and fixing this gonna be pretty complicated :(

**Pull request merged**
