### PR TITLE
Added the ability to mass copy links in different formats

### PR DESCRIPTION
**Pull request by C03**
This fulfills the request to implement the ability to mass copy links when multiple items are selected in the 'history' area https://github.com/ShareX/ShareX/issues/2292.

### CODE REVIEW

**Comment by Jaex** [comment]
It is bad idea to use `OnGetHistoryItems().Length` in that function, especially multiple times. Also you not let opening URL when there is multiple items selected but currently it at least supports opening first URL.

**Comment by C03** [comment]
Hello, thanks for your response. 

I'm open for suggestions on an alternative option to `OnGetHistoryItems().Length` but personally I'm unsure on why it's bad idea to use it. You are completely right about multiple uses, I should have used a local variable to get the count and then used that instead.

As for the opening URL options, I can add it so that it opens all URLs if that would be appropriate? My concern was that if someone had selected 50 URLs and pressed the open option it could cause their browser to crash.

**Comment by Jaex** [comment]
Thanks.

**Comment by Jaex** [comment]
Did you had any reason to not support multi copying in these last 4 buttons?

**Comment by C03** [comment]
I've now added that in https://github.com/ShareX/ShareX/pull/4555

**Pull request merged**
