### PR TITLE
Implementing save changes before closing dialog for the image editor as requested on issue 6725

### PR DESCRIPTION
**Pull request by gregorygregio**
Altered the message box that is presented when closing the image editor without saving changes to ask if the user wants to save them or not, also giving the cancel option to prevent closing the editor. Might need some work in the translations.
Captura_alteracao_ShareX

fixes: [#6725](https://github.com/ShareX/ShareX/issues/6725)

### CODE REVIEW

**Comment by Jaex** [comment]
How did you update all translations?

**Comment by gregorygregio** [comment]
I knew how to translate it to english, spanish and portuguese - which is my native language. All other languages were translated using Google translator.

**Comment by Jaex** [comment]
Sorry but I don't trust Google translator, which I also mentioned at here long time ago: https://getsharex.com/docs/translation

**Comment by gregorygregio** [comment]
I understand. So should I remove the translations? Because the current message would be misleading on what the "Yes" button does.

**Comment by Jaex** [comment]
If text should be changed then you should create a new string resource instead of using old resource.

**Comment by gregorygregio** [comment]
Got it. I will start a new PR from scratch and abandon this one. 
The new PR is #7204

**Pull request closed without merging**
