### PR TITLE
Add Unit Tests

### LINKED ISSUE #4352: Adding Unit and integration tests to project
Hi, Is there a particular reason that Unit and integration tests are not included in project?

Can I add the template and add some unit tests?

### PR DESCRIPTION
**Pull request by pourmand1376**
Closes #4352 .
I've added unit test project template to ShareX called ShareX.UnitTest. I've also added unit tests for Translator helper class.

I plan to write unit and integration tests for whole project.

Thanks for merging.

### CODE REVIEW

**Comment by L1Q** [comment]
This PR is a mess, please take a minute to see how many actual commits you are adding and what they do. Adding Persian? What does it have to do with tests? Are tests for string manipulations even helping anybody?

**Comment by pourmand1376** [comment]
Thanks for informing. @L1Q  
Now, the issue is fixed.

**Comment by AraHaan** [comment]
Dude please fix your commits that don't show your github avatar. Also you know you can rebase push right if you ever had a merge issue? It helped me every time.

**Comment by pourmand1376** [comment]
@AraHaan. Do you know how can I fix them?!

**Comment by pourmand1376** [comment]
Is there something wrong with this PR? 
@Jaex

**Pull request closed without merging**
