### PR TITLE
Reworked German Translation

### PR DESCRIPTION
**Pull request by Kaeltis**
Fixed typos, added lots of missing translations and improved some existing translations

### CODE REVIEW

**Comment by Jaex** [comment]
Thanks.

**Comment by Jaex** [comment]
@Kaeltis are you using Steam? So I can notify you before release.

**Comment by Kaeltis** [comment]
Sure, just add "kaeltis" on Steam :)

**Comment by Jaex** [comment]
There is many Kaeltis on Steam. You must give your profile URL.

**Pull request merged**
