### PR TITLE
Update Lambda URLs

### PR DESCRIPTION
**Pull request by mstojcevich**
No longer have λ.pw -- replaced by lbda.net

### CODE REVIEW

**Comment by Jaex** [comment]
If people already have previous URL in their config, this not gonna replace it?

**Comment by mstojcevich** [comment]
I have removed the domain redirect, so the existing URLs should at least work until I can write a better fix to update the config files that use the old domain (xn--wxa, which is no longer up)

**Comment by mstojcevich** [comment]
The old URL should now be replaced if it's in the config. I'll probably add the ability to set a custom URL in a future PR.

**Comment by Jaex** [comment]
You may want to use `URLHelpers.Combine` for `Config.UploadURL + response.url`

**Pull request merged**
