### PR TITLE
Updated Readme.md

### PR DESCRIPTION
**Pull request by GoldwingStudios**
Deleted some Text- and/or Link-parts in the Uploader Section cause of duplication or pointlessness of the specific link(because they are already mentioned in other sections)

### CODE REVIEW

**Comment by GoldwingStudios** [comment]
why?

**Comment by Jaex** [comment]
Because it is not pointless.

**Comment by GoldwingStudios** [comment]
It is my opinion and I am on the user side so its incommodious and confusing to read. Have you been self-critic on this?

**Comment by Jaex** [comment]
What is self critic means?

**Comment by GoldwingStudios** [comment]
if you questioned yourself whether the text like you wrote it is easily understandable or not. And I think these few links are confusing because they are duplicates of links from the other link sections. you have consider that you are the creator and not a user so you are prejudiced and not objective. So leave it out or put it in.

**Comment by Jaex** [comment]
All entries there just reflecting whats inside ShareX menus. Those "File uploader" in ShareX menus therefore I wrote them.

**Comment by GoldwingStudios** [comment]
so then I would explain this to the user, to make it transparent

**Comment by Jaex** [comment]
Updating readme file very difficult for me and I'm tired asking help from people to fix my english texts.

**Pull request closed without merging**
