### PR TITLE
Add Sinhala(LK) Languange Translation

### PR DESCRIPTION
**Pull request by akalankauk**
Language : Sinhala Translation

### CODE REVIEW

**Comment by Jaex** [comment]
Can you please pull request translations after all translation of app is complete? Because multiple times people partially pull requested them and not completed after that. And on product update release I don't prefer to release language support for new language without it is fully complete.

**Comment by akalankauk** [comment]
Sure. It's completely done! Can you explain which files do i need to upload?

Thanks!

**Comment by Jaex** [comment]
Check here: https://github.com/ShareX/ShareX/pull/3517/files

**Comment by akalankauk** [comment]
I'll add all with a new pull request.

**Pull request closed without merging**
