### PR TITLE
Added functionality to enable hand cursor on pressed shift key for cursor stamp tool in editor.

### PR DESCRIPTION
**Pull request by jbravo94**
Hi maintainers,

as i use ShareX for documentation purposes, i wanted to show also a hand cursor which indicates better that a user should click on something or the screenshotted tool also shows a hand cursor which would then match the edited screenshot.

I compiled and tested the submitted code on my pc.

Best regards,
Johannes

### CODE REVIEW

**Comment by sylveon** [comment]
Does shape options not work?

**Comment by jbravo94** [comment]
F... Didn't got that... Never mind.
Anyways it was fun to think into ShareX, an advanced WPF app.

**Comment by jbravo94** [comment]
@sylveon Do you have some other (minor) issues which i can try to resolve?

**Comment by sylveon** [comment]
Lack of documentation :) You can submit pull requests to the website.

**Pull request closed without merging**
