### PR TITLE
Add indonesian file

### PR DESCRIPTION
**Pull request by Nicedward**
Add indonesian file for ShareX

### CODE REVIEW

**Comment by Jaex** [comment]
What is "Indonesian" in your language?

For this list:

**Comment by Nicedward** [comment]
We call it "Bahasa Indonesia"

**Comment by Jaex** [comment]
Like this?

**Comment by Jaex** [comment]
Thanks for translation!

**Comment by Azhe403** [comment]
how to translate string where not yet translated?

**Pull request merged**
