### PR TITLE
Return download link if the file is not an image

### PR DESCRIPTION
**Pull request by mltnhm**
I noticed this _a bit_ too late, non-images do in fact produce strange previews

### CODE REVIEW

**Comment by Jaex** [comment]
You sent it right after release :(

**Comment by Jaex** [comment]
By the way you can use: `Helpers.IsImageFile(path)`

**Comment by coderobe** [comment]
What about other media data? I'm not sure but i think the preview endpoint works for both audio and video as well.

**Comment by Jaex** [comment]
I never used ownCloud so I have clue.

**Comment by mltnhm** [comment]
I tried it with audio and it just returned a `[]`

**Comment by coderobe** [comment]
Should probably check which files return the correct data (and whether there might be another endpoint that returns the raw data instead of generating a "preview" for some files) instead of creating these case-by-case rules

**Pull request merged**
