### PR TITLE
Add new image uploader (imgland.net)

### PR DESCRIPTION
**Pull request by jibcore**

### CODE REVIEW

**Comment by Jaex** [comment]
Why did you edit readme.md without release it.

**Comment by jibcore** [comment]
Sorry, did you mean that I shouldn't edit readme or what?

**Comment by Jaex** [comment]
Yes why show something in readme without release it yet.

**Comment by jibcore** [comment]
Ok, i can send new pull request without readme.md

**Comment by Jaex** [comment]
No, if you commit it will be added to this pull request automatically.

**Comment by jibcore** [comment]
Yep. I do it.

**Comment by Jaex** [comment]
Thanks.

**Pull request merged**
