### PR TITLE
Fix crashes when starting and closing

### PR DESCRIPTION
**Pull request by sylveon**

### CODE REVIEW

**Comment by sylveon** [comment]
#3738 #3759

**Comment by Truesh00ter** [comment]
When will this be merged into the normal branch and pushed as a new update?

**Comment by sylveon** [comment]
It has been merged 19 minutes ago.

**Comment by Truesh00ter** [comment]
And pushed as a new update: https://i.imgur.com/lMpimbl.png ?

**Comment by sylveon** [comment]
https://getsharex.com/docs/dev-builds

**Pull request merged**
