### PR TITLE
Cleanup and simplify the hotkey selection menu Fixes #2122

### LINKED ISSUE #2122: Add clearer indication to the user in the hotkey settings window when hotkeys are disabled
I filed #2115 yesterday because I managed to disable hotkeys by accident and didn't realize it.  The only clue I had was the color of the boxes on the right side of the screen, which I thought to click on/mouse over, but they don't have any tooltips on them either.

I'd recommend adding tooltips to those boxes, plus some kind of notification bar at the top or bottom of the screen to let the user know that nothing they do in that screen means anything if they don't enable the hotkeys.

### PR DESCRIPTION
**Pull request by stuntguy3000**
Now featuring tooltips.

### CODE REVIEW

**Comment by Jaex** [comment]
I never used {  } in switch case in whole project so it becomes inconsistent.

**Comment by stuntguy3000** [comment]
My Java background is clearly leaking over here. Let me look into what can and can't be done with switches and make the right adjustments.

**Comment by stuntguy3000** [comment]
Corrected.

**Comment by Jaex** [comment]
Sorry but now I check how your changes looks on UI and didn't like color of buttons like this:



Compared to how it is before:



I also asked in Discord server which one people prefers and like me also everyone preferred old one too.

**Pull request closed without merging**
