### PR TITLE
Native Arm64 support

### PR DESCRIPTION
**Pull request by reflectronic**
ShareX runs natively on Arm64 systems with this patch.

In .NET Framework, it is not currently possible to make an AnyCPU EXE that launches natively as Arm64. We use two approaches:

- For the Inno Setup-based installer, we set the `PreferredMachine` option under the `Image File Execution Options` key. This instructs the Windows loader to run ShareX.exe natively as Arm64. Unfortunately, since this key is under `HKEY_LOCAL_MACHINE`, this is only possible when installing as Administrator. I'm not sure if it's worth doing anything more complicated.
- For the Microsoft Store, since setting the registry key is not possible, we need to build ShareX specifically targeting Arm64. We now produce an `msixbundle` file that contains both the x64 `msix` and Arm64 `msix` inside. This file can be uploaded to the Microsoft Store just like the `appx` file used currently. The setup progam and actions workflow have been reworked to read from `win-x64` and `win-arm64` build output folders. (Note that the Inno Setup build is unchanged and uses AnyCPU as before.)

FFmpeg and Recorder-devices are both still x64 emulated. They are still both working on Arm64 though, so it can be left like this for now.

I excluded support for x86 in this patch (since I understand that you will be dropping it in the future) but it would not be difficult to add back if that's desired.

Closes https://github.com/ShareX/ShareX/issues/6653

### CODE REVIEW

**Comment by reflectronic** [comment]
image

**Comment by jimaek** [comment]
Can we get this opened and merged? Especially now with the new wave of good Windows ARM laptops

**Comment by sameeraman** [comment]
Agree! can we please open this again and get it merged ?  Windows is transitioning to ARM rapidly now with the new Snapdragon xElite processors in the market

**Comment by worldsdream** [comment]
+1

**Comment by fizzyfrys** [comment]
Recently got a snapdragon x plus laptop, and would love to install arm64 native shareX on it.
+1

**Comment by kirillrocks** [comment]
+1

**Comment by rexxDZN** [comment]
+1

**Pull request closed without merging**
