### PR TITLE
Next part of Polish translation.

### PR DESCRIPTION
**Pull request by ireun**
Haven't got much time, but many of the most important strings should be
translated now. :)

### CODE REVIEW

**Comment by ireun** [comment]
@Jaex Could you compile a alpha build with everything that I've translated so far, so that I could test it a little bit..?

**Comment by Jaex** [comment]
Someone was wanted to translate ShareX to Polish and I told him that you were worked on it long time ago and probably not gonna finish it. So he could be translating now, not sure. Doing translation part of ShareX and then stopping it more harmful than not doing at all because when people ask is someone translating it or not, I can't even know what to tell. And everytime people start it and stop middle of it and never complete it.

**Comment by ireun** [comment]
I've blocked someone? I've uploaded everything what I've done so far to GitHub, so that if someone else would want to do it after me he would not need to translate everything from the beginning. I could tell you that I've stopped, so sorry for that. But you could just mention me her and ask about it.

**Comment by q012345** [comment]
I was the person who contacted Jaex about Polish translation, I've already done a part of it, but if you @ireun prefer to complete it yourself just let me know. If not, then I'll translate the missing strings based on your partially done translation. Tell me about your decision.

**Comment by ireun** [comment]
Sure, feel free to complete it if you have enough time. Sadly i don't. I just think, that uploading everything that was translated was fine. ;)

**Comment by McoreD** [comment]
I'd think the whole point of open source is collaboration. Someone else can
pick up from where somebody else left off. There is no need to duplicate
efforts. Two or more people should be able complete it using git without
issues.

**Comment by ireun** [comment]
@q012345 can you send me files that you have been working on..?

**Comment by malware1-2** [comment]
First, I'm sorry that it took so much time, I was really busy.
The translation is almost complete, I will probably upload it tonight. Will you be able to provide me a special build with the translation so I can try it out and correct any mistakes?

**Comment by Jaex** [comment]
Yes I can give compiled build.

**Comment by malware1-2** [comment]
I couldn't figure out how I can create a pull request with new files, so I uploaded them here: http://m1.malwarehunterteam.com/files/ShareX.zip
Some strings are still not translated, but most of them are already completed.

**Comment by Jaex** [comment]
In that zip nearly none of the translation files exist?

**Comment by malware1-2** [comment]
Yeah, I forgot to include them. I already removed the comment, I didn't expect that you'll read it.

**Comment by ireun** [comment]
@malware1-2 @q012345 any progress with this? Polish is still not available in the app. ;)

@Jaex Could you enable it? I will translate the rest, as I've translated a bit of the translation long ago. ;)

**Comment by ireun** [comment]
All right, thank You anyway. ;)

**Pull request merged**
