### PR TITLE
Set anchor of label to the bottom-left in TextDrawingInputBox

### PR DESCRIPTION
**Pull request by morsisko**
Before the commit:

After the commit:

### CODE REVIEW

**Comment by Jaex** [comment]
You needed to just change anchor of control, not dock it.

**Comment by morsisko** [comment]
Guess I can't change the content of this PR? Anyway as far as I see the label acts the same (at least visually), no matter if docked or with changed anchor of control.

**Comment by lucario** [comment]
@morsisko Just push the change to the same branch.

**Comment by morsisko** [comment]
Ok, I've changed the dock to "Bottom, Left" anchor

**Comment by Jaex** [comment]
Why did you move control to left.

**Comment by morsisko** [comment]
Sorry, I've ammended the last commit so it is now only plain anchor change to the bottom-left (because as I understand this is the intended position for the label)

**Pull request merged**
