### PR TITLE
[WIP] still-image HDR capture support

### PR DESCRIPTION
**Pull request by imbushuo**
This (draft) PR implements HDR support discussed in issue #3751, #4105, #4570 and #5432. On the high-level overview, it bypasses the old GDI+ capture pipeline using Windows Runtime Graphics Capture API (a wrapper of DXGI Desktop Duplication) while providing a GDI+ compatible 8-bit SDR image that tonemapped from HDR capture source, which covers the majority usage scenarios. A few open questions remain:

# Open questions to be discussed & solved
- Need to choose between reducing overall luminance or clipping while processing the SDR output. The currently implementation reduces overall luminance for final output, similar to what the Xbox Game Bar capture does. On other platforms such as macOS, they decided to clip regions with very high luminance to keep SDR content's brightness. Or alternately, use HLG (?) 
- Which tonemapping algorithm to use? Or let user choose their favorite one? The current PR implementation uses Reinhard, which works well for many test scenarios. But there a few more to consider, like ACES (need to have a D65 white point version though), simple clipping (but something will be washed out) and more.
- Do we need to save the original HDR capture? Not useful for sharing but ideal for post processing out of ShareX.

# Known Caveats
- It doesn't work with scrolling capture, GIF and video capture now. Ideally if video capture switch to this new capture pipeline, it can leverage GPU processing power instead of using ffmpeg.
- A bit more memory usage. Stable 220-400 MB memory usage on a 192GB memory computer with two 4K HDR monitors.

# Sample Captures
msedge_HOgcv742iw
ApplicationFrameHost_LgtASlrQ9z
ApplicationFrameHost_DtfpurTfia
Acbaep2Sqq

### CODE REVIEW

**Comment by craigkc** [comment]
Any chance you're still working on this?  I looked over the code and it appears clean and straight-forward, but it's unlikely I have time to contribute outside of testing.  Without this, I may have to abandon using ShareX, and it seems clear many others are facing the same issue.

Let me know how I can help.

**Comment by imbushuo** [comment]
I think I still have a few corner cases to deal with, and the main author has some concerns regarding introducing external dependency (ShareDX is a lot.) I am currently working on this but the bandwidth is not currently guaranteed.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by craigkc** [comment]
Thanks for the reply.  With SharpDX having halted support some time ago, I can understand the issue there.  I'll take a better look at the rest of the ShareX code to see the prevailing style/intent and see if I can help.  I don't want to pollute your PR like an issue discussion, so I'll leave it at that for now.

**Comment by rmarskell** [comment]
I would like to see this issue re-opened as there are currently no open HDR issues and this issue seems to be the most promising. This is still a big problem for those of us with HDR enabled.

**Comment by rikai** [comment]
This is something that has been a personal annoyance to me, as it regularly ruins my screenshots on any HDR-enabled system that has HDR enabled.

I did see that there was hesitation to use SharpXD because it had been continued, however it does look like there are a couple of alternatives available that seem to have at least some level of HDR-awareness/support:

[Silk.NET](https://github.com/dotnet/Silk.NET) (official .net foundation project)
[Vortice](https://github.com/amerkoleci/Vortice.Windows) - independent, but actively maintained

Unsure if these projects are actually suitable for the use case, but I thought I might mention them. :)

**Comment by WDD3MS** [comment]
I have the same problem with HDR. (LG monitor + AMD 5600G (Vega7 ) via DP]
Usually the captured image is heavily overexposed.

**Comment by pish180** [comment]
This is marked as closed but it still an issue.  Any reason this wasn't merged?

**Comment by SalmonSays** [comment]
This really should get merged.

**Comment by WDD3MS** [comment]
I notice this only on EDGE.

**Comment by ividyon** [comment]
Any news? This is vital for anyone trying to use HDR displays.

**Comment by WDD3MS** [comment]
I have still this problem. 
Only on EDGE, and some web is okay, some don't. 
Even on the same page, and on the same feed (live updated) some news part with picture - overexposed, some - ok.

**Comment by diff-by-default** [comment]
+1

This would be a quality of life gamechanger for almost everything I do at my computer these days. HDR is everywhere and this issue is only getting worse with windows 11 having auto HDR.

**Comment by spartaque12** [comment]
its been several years, still no fix, amazing

**Comment by rmarskell** [comment]
> its been several years, still no fix, amazing

Yeah, the dev has said it doesn't affect them so they're not interested in fixing it. 🤷

Also, I've tried running the branch for this PR and it didn't seem to work for me. I may have been doing something wrong though. Not 100% sure.

**Comment by MRDGH2821** [comment]
Any chance this is still worked on?

**Comment by ScottRFrost** [comment]
Still a problem in the 16.x.x series

**Comment by Psyda** [comment]
Still a problem. Any ideas? 
QfHoRHY 1

**Comment by ScottRFrost** [comment]
For anyone finding this (after years) via search / etc, as a temporary workaround, you can do a HDR friendly screen capture on Windows 11 by Press Windows Key + Alt + Printscreen, which will save the file by default to C:\Users\YourUsernameHere\Videos\Captures

You can then load this image into any normal photo editing app (such as paint.net) to mark it up before sending

Hopefully we won't need this workaround once ShareX supports HDR natively!

**Pull request closed without merging**
