### PR TITLE
Fixed #532: Filename text length will now check/uncheck 'Filename filter...

### LINKED ISSUE #532: Search field - key listener
On history page can you add event listener on EnterKey for apply filters?
And on first letter inserted in Filename filter set checkbox checked?
http://i.imgur.com/bkTwydL.jpg

Often I write search term, press Enter and find out that I need to take mouse and klick on checkbox and Apply filters.

### PR DESCRIPTION
**Pull request by ElectricDanDan**
...' checkbox. 'Apply filters' button now default accept button.

Not sure why GitHub is showing it as wanting to change hundreds of lines in the Designer and resx files, when it's actually just a few lines here and there. Perhaps it's that I've got Visual Studio set to use tabs instead of spaces?

### CODE REVIEW

**Comment by Jaex** [comment]
Yes it is because of tabs and I wrote here therefore: https://github.com/ShareX/ShareX/wiki/Code-contribution
That I only accept pull requests with spaces.

Also this not solves #532 because he want search to happen when typing but yours just checking it. So it is not what he wants.

**Comment by ElectricDanDan** [comment]
Okay, well I will change Visual Studio to use spaces instead.

If you read #532 again you'll see that this commit does actually meet his request. He doesn't ask for a history search, he just wants the 'Filename filter' checkbox to be checked when there is text in the filename textbox. He just wants to be able to type a filter and press enter.

I will change to spaces and make another pull request of the same solution, which will meet his issue and not affect performance.

**Comment by Jaex** [comment]
"On history page can you add event listener on EnterKey for apply filters?"

Which means when you press key it will apply filters. So this pull request not meet his request.

**Comment by ElectricDanDan** [comment]
"On history page can you add event listener on **EnterKey** for apply filters?"

He wants to be able to press the enter key on his keyboard and have it behave the same as clicking the 'Apply filters' button.

**Comment by Jaex** [comment]
Oh I thought enter key means press key.

**Comment by MilanRS** [comment]
ElectricDanDan is right. I don't know how you name that EnterKey, Return key, that key for new line and form submit. :)

**Comment by Jaex** [comment]
I'm reverting `AcceptButton` change because it not allows list to open URLs with <kbd>Enter</kbd>.

**Pull request closed without merging**
