### PR TITLE
Added Size and SizeMode properties to the image watermark effect

### PR DESCRIPTION
**Pull request by RedMser**
Implements the suggestion of #3157.

`SizeMode` has the following values:
- `AutoSize`: size is determined by the image's size, the `Size` property does nothing
- `Absolute`: size is determined by the `Size` property, in pixels
- `Percent`: size is determined by the `Size` property, as a relative percentage of the image's size

### CODE REVIEW

**Comment by Jaex** [comment]
Don't you think auto size is misleading when it is not resizing at all?

**Comment by RedMser** [comment]
What is your proposed solution? You can't easily disable properties in the editor.
I thought about automatically changing the mode when you specify a size, and vice versa, but not sure how it'll work out with programatically setting the values.

**Comment by Jaex** [comment]
This:

>  //TODO: Is a custom enum for different watermark image sizes a better idea?

**Comment by RedMser** [comment]
Right, if it's only a matter of naming, I have created a custom enum `DrawImageSizeMode` with the values renamed to `DontResize`, `Absolute` and `Percentage` respectively. Should be clear now that the default value won't actually do anything with the `Size` property (but of course, alternatively the `Size` property could be populated when loading an image, and use `Absolute` scaling then...).

**Comment by Jaex** [comment]
Relative mode also can be added. For example if you want watermark to be 20% size of image size.

**Comment by Jaex** [comment]
Percentage can be misleading too because people can think it is percentage of inserted image instead of relative percentage to source image.

**Pull request merged**
