### PR TITLE
Update chinese translation

### PR DESCRIPTION
**Pull request by Jeffiy**

### CODE REVIEW

**Comment by Jaex** [comment]
You are adding references to csproj also adding pl and cs language resx files when those are not completed.

**Comment by Jaex** [comment]
Removed those cs.resx and pl.resx files now because those were not in use and never gonna be completed.

**Comment by Jeffiy** [comment]
Oops， I didn't see that, I will remove them tomorrow, sleeping now, good night.

**Comment by Jeffiy** [comment]
Done, /cc @Jaex

**Comment by Jaex** [comment]
Thanks.

**Pull request merged**
