### PR TITLE
Polish Translation

### PR DESCRIPTION
**Pull request by karnasw**
Add polish translation.

### CODE REVIEW

**Comment by karnasw** [comment]
> 
> 
> This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

Is anything wrong with this  translation?

**Comment by Jay-Tarzan** [comment]
:) all for nothing

**Review by Jay-Tarzan — APPROVED** [review]

**Comment by L1Q** [comment]
> > This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.
> 
> Is anything wrong with this translation?

it modifies ``ShareX/Forms/ClipboardUploadForm.resx ``

**Comment by arlido** [comment]
I would like to translate software to Polish, how can i do that? I read https://getsharex.com/docs/translation, but I want to know which files download and how post them to author. Translation isn't a problem, but post new files is. Can someone write how to do that correctly?

**Pull request closed without merging**
