### PR TITLE
Dutch Translation

### PR DESCRIPTION
**Pull request by wforums**
All strings are translated to Dutch.

### CODE REVIEW

**Comment by Jaex** [comment]
Thanks for translation.

**Comment by Jaex** [comment]
If you can't compile ShareX yourself and want to test it, let me know so I can compile it for you.

**Comment by wforums** [comment]
If you could compile it for me it would be nice :)

**Comment by Jaex** [comment]
https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/05/ShareX-9.10.0-setup.exe

**Comment by wforums** [comment]
I'll check it over entirely and if there's any corrections that need to be made, I'll add them later this day/week :)

**Pull request merged**
