### PR TITLE
New translation: Portuguese Brazil

### PR DESCRIPTION
**Pull request by TiagoDanin**

### CODE REVIEW

**Comment by Jaex** [comment]
Thanks for translation.
When adding it to languages list should I write Portuguese? Is there any difference between Portuguese and Brazil Portuguese?

**Comment by TiagoDanin** [comment]
Differentiates changes a little when and names objects and places.
And more in the speech that changes.
Can be uses as Portuguese of Portugal quietly.
Any questions just call.

Good luck with the project.

**Comment by Jaex** [comment]
I didn't got answer to my questions. Should I list your language as Portuguese or Brazil? Should I change your files to "pt" for automatically detect Portugal users to use your language? I don't know what to do.

**Comment by TiagoDanin** [comment]
Brasil.

**Comment by TiagoDanin** [comment]
Created one for portugal in 12 days. So get better.

**Comment by TiagoDanin** [comment]
Portuguese, sever for the 2 languages.

**Comment by TiagoDanin** [comment]
Portuguese, caters to the 2 languages.

**Comment by Jaex** [comment]
Then why you used pt-BR so it won't work for Portugal users.

**Comment by TiagoDanin** [comment]
A few words will change to Portugal as:
Br: Ícone na barra de tarefas Pt: Ícone na bandeja
Br: Abridor Pt: tira-cápsulas
Br: file Pt: fila, bicha ...

**Comment by Jaex** [comment]
I added it as "Portuguese-Brazil":



If you want I can compile build so you can test it.
By the way saw some buttons missing "..." in main window menus.

**Comment by TiagoDanin** [comment]
I would like to see before, so tests be this all ok.

**Comment by Jaex** [comment]
You not using Google Translate right?

**Comment by TiagoDanin** [comment]
Bing Translator, don't use anything from google.
For me and difficult to write in English.
I know Spanish, French and Portuguese (in Brazil).
I'm learning Japanese.
I can only read English. Get lost in conjugations and verbs.

**Comment by Jaex** [comment]
So this is why barely I can understand anything you tell. And with this bad english you still translated ShareX ?! Did you not read here https://github.com/ShareX/ShareX/wiki/Translation in top it tells "Fluency in English" is required.
You must be used Bing Translator in majority of ShareX translations now and nothing would be understandable for users. It is better for people to use English than using machine translated software. Because machine translation nearly not understandable, it is beyond bad. This is far from acceptable. I seriously can't believe how when you can't write anything in english and still translated it using web site.

**Comment by TiagoDanin** [comment]
The ShareX don't. My plublicaçoes here.
I used the ResX to translate, I left it the way it is in the image below:


More if I didn't think I should do the translation public schedule and her.

**Comment by McoreD** [comment]
One of the main requirements for translation is fluency of English. Please refrain from using machine translation. https://github.com/ShareX/ShareX/wiki/Translation guidelines are here. 

Do you not think that we could have translated ShareX to over 60 languages by ourselves if we used Google or Bing translator? The reason why we have not got that many translations in ShareX is because we rely on users to use their fluency to translate each phrase accurately and appropriately.

**Pull request merged**
