### PR TITLE
#5337 rearranged tools menu in tray

### PR DESCRIPTION
**Pull request by DylanMurphey**
Added separators as well between @yashpalgoyal1304's segments

### CODE REVIEW

**Comment by yashpalgoyal1304** [comment]
hi there, thanks for taking it up. I just noticed that video thumbnailer can be moved up so that it is just next to image thumbnailer. Views??

**Comment by DylanMurphey** [comment]
Makes sense, done! This'll hopefully be my last commit on this. Preview below.

image

**Comment by yashpalgoyal1304** [comment]
is inspect window a new feature?? I have 13.4 and this is not shown to me. {i have checked the @getsharex twitter - as devt features were posted there earlier too, and it's not there as well}

**Comment by DylanMurphey** [comment]
> is inspect window a new feature?? I have 13.4 and this is not shown to me. {i have checked the @getShareX twitter - as devt features were posted there earlier too, and it's not there as well}

Yeah it was added in 8f2d3bd31cd43f852043703bfb1002dc67bb1728. It's on the dev build if you're interested but it's not the most exciting feature.

**Comment by yashpalgoyal1304** [comment]
bad bot go away

**Comment by yashpalgoyal1304** [comment]
bot bot i told u to go away

**Comment by yashpalgoyal1304** [comment]
oh god, this bot is soo buggy 🤕  \
but still have soo much privilages.

**Comment by yashpalgoyal1304** [comment]
> Jaex closed this in https://github.com/ShareX/ShareX/commit/10467931143d4bd36aa2c4727e601c27152788ec x days ago
> _- [#5337 (event)](https://github.com/ShareX/ShareX/issues/5337#event-4854119065)_

this MR can be closed, but thanks a lot anyways @ DylanMurphey

**Pull request closed without merging**
