### PR TITLE
Spanish translation complete

### PR DESCRIPTION
**Pull request by ovnisoftware**
Everything has been translated, just need to add a Spanish language option in ShareX Application Settings and I will review it from there to see what further changes are needed.

### CODE REVIEW

**Comment by Jaex** [comment]
Thank you! I'm adding Spanish language to settings now.

**Comment by Jaex** [comment]
Used "Español (Spanish)" for application settings and "es-ES" for language code, are these right?

By the way this menu when bigger looks bad:

**Comment by ovnisoftware** [comment]
The language code and application settings must be right because when I switch to Spanish in the application settings it uses the .es files.

I'm going to change some of the names on the main form so they are shorter.  I'm also going to check to see if anything is getting cut off in any of the buttons so I can shorten those as well.

Could you add my Github contact info on the About page so that people can contact me if they have questions about the translation?

**Comment by Jaex** [comment]
You don't need to remind me to add you to about page.

**Pull request merged**
