### PR TITLE
Add pomf.lesderid.net to Pomf.cs

### PR DESCRIPTION
**Pull request by lesderid**

### CODE REVIEW

**Comment by Jaex** [comment]
Why you added `https://pomf.lesderid.net/f`? Your response already contains full url. It is only required for people who using old version of pomf which not returns full url.

**Comment by lesderid** [comment]
Whoops, I didn't notice the difference. I couldn't actually test it since I'm not on Windows. I fixed it and added my clone to the readme.

**Comment by Jaex** [comment]
Don't add anything to read me. Otherwise people will see it and wonder why it is not exist in current release. Read me supposed to update after release not before.

**Comment by lesderid** [comment]
Makes sense. Removed it from the readme.

**Pull request merged**
