### PR TITLE
Improvements for OwnCloud / NextCloud

### PR DESCRIPTION
**Pull request by pathosDev**
**Hi there :wave:**

in the last few days I added some features to the OwnCloud / NextCloud uploader.

## 1) Path filtering

Some time ago I and a friend of mine (thanks to @anaether at this point) talked about the possibility to upload different files into different folders in OwnCloud / NextCloud like its done for "FTP / FTPS / SFTP". For example uploading images, text files and other files to different locations. This is why I added a path filtering feature to OwnCloud / NextCloud. Therefore just tick the checkbox "Enable path filters" and some new controls will appear:

Imgur

#### But how do they work?

To add a new filter just click the "+" button to the right of the list. Now you have a new filter! You can also remove filters by clicking "-". A filter uses the **regular C# RegEx** to upload different files to different locations. If uploading an image the filters will be applied to the filename. The first filter that matches the filename with a given RegEx will be used for uploading (going through from top to bottom). That's why I also added buttons to sort the filters. To edit the filters use the textboxes below. If no filter matches the file the default folder ("Common path") will be selected for uploading.

### 1.1) Some example filters

If enabling the path filters for the first time I added some example filters:

Imgur

These sample filters just sort the files based on their file extension in different folders (I just added the most common file extensions). The filters themselfes are very self explanatory. Here are the complete filters:

```
Path: "/Share/Archives"
Filter: "\.(7z|bz2|cab|dmg|gz|iso|lz|lz4|lzma|pak|rar|tar|xz|zip|zst)$"

Path: "/Share/Audio"
Filter: "\.(3gp|aa|aa3|aac|aax|aiff|flac|m4a|mp3|ogg|oga|opus|tta|wav|wma)$"

Path: "/Share/Documents"
Filter: "\.(doc|docm|docx|pages|pdf|ppt|pptx|latex|odp|ods|odt|rtf|tex|xls|xlsx)$"

Path: "/Share/Images"
Filter: "\.(ai|bmp|dds|eps|gif|ico|jpg|jpeg|png|psd|svg|tga|tiff)$"

Path: "/Share/Text"
Filter: "\.(bat|c|cfg|cpp|cs|csv|h|hh|hpp|htm|html|ini|java|js|log|lua|md|php|pl|py|rb|sh|txt|vb|xml)$"

Path: "/Share/Videos"
Filter: "\.(3g2|3gp|amv|asf|avi|flv|m4v|mkv|mov|mp4|mpg|mpeg|ogv|webm|wmv)$"
```

### 1.2) Realtime RegEx validation

RegEx can be frustrating some time. So as a little gimmick I implemented a realtime RegEx validation. If you enter an invalid C# RegEx ShareX will now tell you:

Imgur

> **Tip:** You can also check your RegEx on this awesome site: https://regex101.com/

### 1.3) Using RegEx groups

It is also possible to sort files to filename specific folders. That can be done using RegEx group matching. E.g. lets have a look at this filter:

```
Path: "/Share/Files/%1"
Filter: "\.(.*)$"
```

If you would now upload a `.png` file the upload folder would be `/Share/Files/png`. This works for all file extensions because RegEx is universal. Another example: Uploading files based on their beginning and then sorting them after their extension:

```
Path: "/Share/Files/%1/%2"
Filter: "^(.*)_.*\.(.*)$"
```

As you already saw matched groups will be replaced by `%{group_number}`. The full match is represented by `%0` respectively.

This feature _could_ be extended in the future with uppercase, lowercase, pascalcase string replacement etc.

## 2) Automatically create folders

The RegEx group replacement feature (see 1.3) is only very useful if ShareX creates the folders by itself if they do not already exist. Otherwise that feature would be very limited.

Imgur

When enabling this option and a folder doesn't already exist it can take some seconds. I managed to improve the performance of the folder creation to a maximum and the number of requests to a minimum. If a folder already exists the folder check is not very noticeable (less than half a second).

## 3) Password encryption

When developing these features I noticed that all passwords were stored as clear text in the settings file and I'm not a big fan of this. So I added the possibility to encrypt your OwnCloud / NextCloud password in the settings file.

Imgur

For the encryption I used [DPAPI](https://en.wikipedia.org/wiki/Data_Protection_API) ([Link to C# reference](https://en.wikipedia.org/wiki/Data_Protection_API) (https://docs.microsoft.com/en-US/dotnet/api/system.security.cryptography.protecteddata)). It is very simple to use and secure. It can only be decrypted on your personal user account and machine. But it is important to mention that this will maybe only work on windows machines since this is a microsoft only feature. I enabled this option as default. This is how it looks:

```
Without encryption: "abcdefg"
With encryption: "AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAALOu0fb+UCkeq9kFohmRDqAAA..."
```

Maybe this is some food for thought and it can be implemented for all passwords and other sensitive data in the settings file. I didn't have the time so I just implemented it for OwnCloud / NextCloud.

## 4) Reveal password

While implementing the password encryption I often struggled with the question "Did it now use the correct password or not?". So I quickly build a solution for this and left it in there. You can now reveal your password when clicking on the eye next to the password field.

Imgur

## 5) German translation

Because I'm a german citizen I updated the german translation a little bit. I will maybe update it a little bit more in the future :wink:

---

I hope you find this features as usefull as I do :smile:

Best greetings and stay healthy :v:

### CODE REVIEW

**Comment by McoreD** [comment]
Well documented! Thanks!

**Comment by Jaex** [comment]
Impressive work @pathosDev!

Are you using Discord, Steam or Telegram? I need to discuss about few things, especially about password encryption support. And using chat client will be easier for us instead of going back and forward in here.

**Comment by JensKillermann** [comment]
When will this change be merged?
Great change.

**Comment by pathosDev** [comment]
> When will this change be merged?
> Great change.

Hi there :wave:

I had a lot of stuff to do since then...
I also already spoke with @Jaex about some features at that time. For example, he already added the password encryption.
I will try to adapt it to the current ShareX version really soon (I mean if I can find time for it 😄)
It is already on my todo list.

Best greetings

**Pull request closed without merging**
