### PR TITLE
Auto save OCR result

### PR DESCRIPTION
**Pull request by YueLinHo**
Save the OCR result to the same name txt file:
image

### CODE REVIEW

**Comment by Jaex** [comment]
Thanks.

**Comment by YueLinHo** [comment]
@Jaex Thank you so much.

**Comment by bmidy** [comment]
Hi All,

First thanks to you for this great Tool !!
I d like to use this but I got no success.


My working day is like this.
I use a lots of screenshot, and later I d like to have the possibility to search in my Screenshot folders for some texts.

So I d like to have an Auto OCR of the Screenshots done, and like said above

to have the resulting OCR in the same folder, with same filename, date, just with a .txt etxension instead of .png

Accoring to this post it  seems to be OK, but I could not ??

Thanks

**Comment by jeifour** [comment]
Hi, this seems really useful. However, I don't understand how to achieve this result. @YueLinHo could you give me a hint how this works?

**Pull request merged**
