### PR TITLE
Vietnamese translation added

### PR DESCRIPTION
**Pull request by thanhpd**
Hello, this is my first translation, it is ready for production stage. There are still some issues with the translation which will be addressed soon.

### CODE REVIEW

**Comment by Jaex** [comment]
Wow you translated it so quickly, under two days?

By the way did you committed ShareX.ScreenCaptureLib.csproj file by mistake? I will revert it after merge.

**Comment by thanhpd** [comment]
This week I am having more free time than it should so this translation kept me occupied. And yes, ShareX.ScreenCaptureLib.csproj is added by mistake, my apology.
I'm gonna do a review of my translation soon, although I've checked it already.
Maybe I'll do a new uploader next? I see Bitbucket or 4shared is not here.

**Comment by Jaex** [comment]
Someone working on Bitbucket I think: https://github.com/ElectronicWar/ShareX/commits/feature-snippets

**Comment by Jaex** [comment]
Can you write your language like this: Deutsch (German) so i can add it to list.

**Comment by thanhpd** [comment]
You can use this: Tiếng Việt (Vietnamese)

**Pull request merged**
