### PR TITLE
Restore mpql to credits

### PR DESCRIPTION
**Pull request by mpql**
Hello McoreD and Jaex! 👋

Y'all might remember me as Mopsy or Mopquill; I made the original ShareX logo for you (inspired by a camera shutter and a pinwheel) way back in the 2010 - 2012 range when we were differentiating from ZScreen and did the whole ShareXmod thing. I noticed y'all have iterated on the logo (and that's good!), but I would still like credit for the design. I did mention this a while back, but I think we probably all lost track of it (Hangouts / Google Code was a mess, and I no longer use Hangouts, haha).

I'm not sure what order the credits are meant to be in, so I just added it to the bottom of the "Credits" section, trying to follow the existing conventions. I've enabled edits on this PR, so feel free to move it around as y'all see fit; apologies in advance if I did something out of place there.

Also, I'm in the ShareX Discord as Mopsy; feel free to add me if you'd like to chat or catch up! I hope y'all are doing well! 😊

\- mpql

### CODE REVIEW

**Comment by mpql** [comment]
@McoreD @Jaex it's been a month, so I'm pinging you.

**Comment by McoreD** [comment]
Hi Mopsy,

Good to hear from you. 

In regard to the new ShareX icon, I feel like you have forgotten our Google Chat 9 years ago. I have taken a screenshot as below.

It is very evident that other than not liking the new icon, you had no any other issues with the change:
https://github.com/ShareX/ShareX/commit/4cfaf8618451caec026829ac3c09a344eebf07d9

telegram-cloud-photo-size-4-6009060655203725252-w

Nearly 10 years later, and also for a new icon, asking for credits is an unreasonable and invalid request. 

Best regards,
Mike

**Comment by mpql** [comment]
Hey Mike! Good to hear from you, too! I don't use Hangouts anymore, so I've had no idea how to contact you, haha. Hope you and your wife are still doing well! :D

> In regard to the new ShareX icon, I feel like you have forgotten our Google Chat 9 years ago. I have taken a screenshot as below.

I have not forgotten that chat, actually! I told that story to a colleague recently about an icon design being a "third-party dependency", and besides getting a laugh, having heard of the ShareX project, they were surprised y'all'd snub a contributor like that. I said it was likely just us being young, open-source being young*er* than it is now, and they suggested I reach out and file a PR.

> It is very evident that other than not liking the new icon, you had no any other issues with the change

I disagree that I had no issue with the change, and I'm clearly requesting the credit link even in that screenshot there; I don't see me offering any consent to have it removed. And I'll tell you: I definitely felt disappointed at the time. Having put a good deal of work into improving the logo assets and the icon scaling at the time there, and knowing that that got thrown away without any communication beforehand felt bad. I spoke to Berk about it at the time, and I recall him interrogating me about whether I'd used a tutorial for Illustrator (I had, as I designed the logo in Fireworks at the time, but was less familiar with Illustrator and wanted to vectorize it), and he was honestly pretty rude about it. I have all those old conversations from years back, but I don't think dredging them up now is the play here.

> Nearly 10 years later, and also for a new icon, asking for credits is an unreasonable and invalid request.

I strongly disagree. I designed that logo on the heels of the switch from ZScreen, "ZUploader", etc., and it was based on both a camera lens and a multi-colored pinwheel -- that design gave it recognizability, and ultimately a brand, and those foundational elements persist to this day. Before that, I believe it was a small blue camera with an eyeball on it or something, and there was that "ZU" logo at one point too: (image). Iterating on the logo and updating the brand over time is expected, and changing the assets is obviously fine, but ignoring that I *designed* the logomark in the first place and disavowing my contributions is unreasonable. To draw an analogy, if I contributed code in the past that has since been updated so as to be replaced, would you remove me from the contributors then?

I'll also add that I had some serious imposter syndrome back then, and I habitually let people take credit for my work, underpay me, etc. I stopped trying to help sort tickets back when we were still on `svn` on Google Code specifically because of Berk's toxic attitude at the time -- even toward you. I decided I couldn't work with him, and decided not to work on the project. In all honestly, I assumed there would have been a lot of growth since then and this would be a no-brainer, so I'm puzzled at the resistance here.

Having said that, using how he chose to treat me and my work then as justification for continuing to do so now is bananas. So, when I told that story and my colleague suggested I try to restore my credit, I thought about it and decided it was both fair, and in-line with my values nowadays, as well as how I feel the open source community has become. And even having seen your reply, I still feel that way.

I, you, and Berk all know I designed the ShareX logo. The messed up part is that I've been left out all this time. I think it's only fair to credit me as such now. I hope you'll do the right thing here.

**Comment by mpql** [comment]
And in case this is a logical sticking point, branding and logo *design* isn't the same as *graphical asset production*. Berk produced the most recent asset based on my design.

To relate it to code: this is the difference between software architecture and software programming.

**Pull request closed without merging**
