### PR TITLE
Replaced Norton ConnectSafe with CleanBrowsing as it was discontinued.

### PR DESCRIPTION
**Pull request by JimmyHoke**
Norton ConnectSafe has been discontinued recently. https://connectsafe.norton.com/
This PR replaces it with CleanBrowsing.

### CODE REVIEW

**Comment by Jaex** [comment]
What is CleanBrowing never heard of it before. I only added known reputable DNS to list.

**Comment by JimmyHoke** [comment]
They are fairly well known.  If you Google them you will find many articles recomending them.

**Comment by JimmyHoke** [comment]
@Jaex. Should I remove CleanBrowsing from the list?

**Comment by Jaex** [comment]
Yes.

**Comment by JimmyHoke** [comment]
Ok I removed CleanBrowsing.

**Pull request merged**
