### PR TITLE
Handle multiple context menu selections - Fixes #770

### LINKED ISSUE #770: Context menu uploading doesn't add the files in order and duplicates files in list
Number of files to be uploaded: 24
Image

Queued files:
Image in queue

Mega error:
Mega

### PR DESCRIPTION
**Pull request by campbeb**
The problem is that multiple context menu selections spawn multiple .exe
(invoked). Each invoked .exe sets the `InstanceProxy` variables in the
running .exe and tells it to start a thread to process. But, there is no
waiting, so the `InstanceProxy` variables get clobbered before the spawned
thread can process them.
This fix uses a semaphore to control the invoked .exe. There is only one
entry allowed forcing invoked .exe to wait until any other invoked .exe
is finished running and releases the semaphore.

Fixes #770

### CODE REVIEW

**Comment by Jaex** [comment]
Thanks.

**Comment by Jaex** [comment]
I did few testings using these files:



Most of the times few files was duplicate in ShareX main window list:



So your solution is not reliable too unfortunately.

**Comment by campbeb** [comment]
Can you verify that your context menu was invoking your test build and not some other copy of the exe on your computer?

**Comment by Jaex** [comment]
Yes it was my test build. Without test build majority of them becomes same file.

**Comment by campbeb** [comment]
I apologize for the incomplete solution. It worked on my computer.
I've made a change and will open a new PR.

**Pull request merged**
